# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-14 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bookinfo',
            managers=[
                ('books', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='image',
            field=models.ImageField(null=True, upload_to='pid', verbose_name='图片'),
        ),
    ]
